### ISSUE TITLE
`TR-` is "terre", overwriting "intérêt" from `tao_la_salle.json`

### ISSUE THREAD

**Issue by Vermoot** [Vermoot/Pluvier#4]
The outline `"TR-": "intérêt"` *is* in the generated dictionary, but it's being overwritten by the generated `"TR": "terre"` outline (as referenced in #2).

I think the `tao_la_salle.json` entries should be added at the end of the file, so they take priority?

**Comment by stl74** [comment]
tao_la_salle has been added at the end of the file.
